"""init tables

Revision ID: b6a31168d666
Revises: 
Create Date: 2025-12-31 17:14:04.226890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6a31168d666'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_announcement',
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='摘要'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: draft/published/expired'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='优先级: 0普通/1重要/2紧急'),
    sa.Column('is_top', sa.Boolean(), nullable=True, comment='是否置顶'),
    sa.Column('target_type', sa.String(length=20), nullable=True, comment='接收范围类型: all/dept/role/user'),
    sa.Column('target_ids', sa.JSON(), nullable=True, comment='接收目标ID列表'),
    sa.Column('publish_time', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('expire_time', sa.DateTime(), nullable=True, comment='过期时间'),
    sa.Column('publisher_id', sa.String(length=50), nullable=True, comment='发布人ID'),
    sa.Column('read_count', sa.Integer(), nullable=True, comment='阅读次数'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_announcement_is_deleted'), 'core_announcement', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_announcement_priority'), 'core_announcement', ['priority'], unique=False)
    op.create_index(op.f('ix_core_announcement_status'), 'core_announcement', ['status'], unique=False)
    op.create_table('core_announcement_read',
    sa.Column('announcement_id', sa.String(length=50), nullable=False, comment='公告ID'),
    sa.Column('user_id', sa.String(length=50), nullable=False, comment='用户ID'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='阅读时间'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_announcement_read_unique', 'core_announcement_read', ['announcement_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_core_announcement_read_announcement_id'), 'core_announcement_read', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_core_announcement_read_is_deleted'), 'core_announcement_read', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_announcement_read_user_id'), 'core_announcement_read', ['user_id'], unique=False)
    op.create_table('core_dept',
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名称'),
    sa.Column('code', sa.String(length=32), nullable=True, comment='部门编码'),
    sa.Column('dept_type', sa.String(length=20), nullable=True, comment='部门类型'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='部门电话'),
    sa.Column('email', sa.String(length=64), nullable=True, comment='部门邮箱'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='部门状态'),
    sa.Column('description', sa.Text(), nullable=True, comment='部门描述'),
    sa.Column('parent_id', sa.String(length=21), nullable=True, comment='父部门ID'),
    sa.Column('lead_id', sa.String(length=21), nullable=True, comment='部门领导ID'),
    sa.Column('level', sa.Integer(), nullable=True, comment='部门层级'),
    sa.Column('path', sa.String(length=500), nullable=True, comment='部门路径'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_dept_code'), 'core_dept', ['code'], unique=True)
    op.create_index(op.f('ix_core_dept_dept_type'), 'core_dept', ['dept_type'], unique=False)
    op.create_index(op.f('ix_core_dept_is_deleted'), 'core_dept', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_dept_level'), 'core_dept', ['level'], unique=False)
    op.create_index(op.f('ix_core_dept_name'), 'core_dept', ['name'], unique=False)
    op.create_index(op.f('ix_core_dept_parent_id'), 'core_dept', ['parent_id'], unique=False)
    op.create_index(op.f('ix_core_dept_path'), 'core_dept', ['path'], unique=False)
    op.create_index(op.f('ix_core_dept_status'), 'core_dept', ['status'], unique=False)
    op.create_table('core_dict',
    sa.Column('name', sa.String(length=100), nullable=False, comment='字典名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='字典编码'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_dict_code'), 'core_dict', ['code'], unique=True)
    op.create_index(op.f('ix_core_dict_is_deleted'), 'core_dict', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_dict_name'), 'core_dict', ['name'], unique=False)
    op.create_index(op.f('ix_core_dict_status'), 'core_dict', ['status'], unique=False)
    op.create_table('core_dict_item',
    sa.Column('dict_id', sa.String(length=36), nullable=False, comment='字典ID'),
    sa.Column('label', sa.String(length=100), nullable=True, comment='显示名称'),
    sa.Column('value', sa.String(length=100), nullable=True, comment='实际值'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='图标'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_dict_item_dict_id'), 'core_dict_item', ['dict_id'], unique=False)
    op.create_index(op.f('ix_core_dict_item_is_deleted'), 'core_dict_item', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_dict_item_label'), 'core_dict_item', ['label'], unique=False)
    op.create_index(op.f('ix_core_dict_item_status'), 'core_dict_item', ['status'], unique=False)
    op.create_index(op.f('ix_core_dict_item_value'), 'core_dict_item', ['value'], unique=False)
    op.create_table('core_file_manager',
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件/文件夹名称'),
    sa.Column('type', sa.String(length=10), nullable=True, comment='类型: file/folder'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父文件夹ID'),
    sa.Column('path', sa.Text(), nullable=False, comment='文件路径'),
    sa.Column('size', sa.BigInteger(), nullable=True, comment='文件大小(字节)'),
    sa.Column('file_ext', sa.String(length=50), nullable=True, comment='文件扩展名'),
    sa.Column('mime_type', sa.String(length=200), nullable=True, comment='MIME类型'),
    sa.Column('storage_type', sa.String(length=20), nullable=True, comment='存储类型: local/oss/minio/azure'),
    sa.Column('storage_path', sa.Text(), nullable=False, comment='存储路径'),
    sa.Column('url', sa.Text(), nullable=True, comment='访问URL'),
    sa.Column('thumbnail_url', sa.Text(), nullable=True, comment='缩略图URL'),
    sa.Column('md5', sa.String(length=32), nullable=True, comment='文件MD5'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='是否公开'),
    sa.Column('download_count', sa.Integer(), nullable=True, comment='下载次数'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_file_manager_is_deleted'), 'core_file_manager', ['is_deleted'], unique=False)
    op.create_index('ix_file_manager_md5', 'core_file_manager', ['md5'], unique=False)
    op.create_index('ix_file_manager_parent_type', 'core_file_manager', ['parent_id', 'type'], unique=False)
    op.create_index('ix_file_manager_storage_type', 'core_file_manager', ['storage_type'], unique=False)
    op.create_table('core_login_log',
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='用户ID'),
    sa.Column('username', sa.String(length=150), nullable=False, comment='用户名'),
    sa.Column('login_type', sa.String(length=20), nullable=True, comment='登录方式'),
    sa.Column('status', sa.Integer(), nullable=True, comment='登录状态'),
    sa.Column('failure_reason', sa.Integer(), nullable=True, comment='登录失败原因'),
    sa.Column('failure_message', sa.String(length=255), nullable=True, comment='登录失败详细信息'),
    sa.Column('login_ip', sa.String(length=50), nullable=False, comment='登录IP地址'),
    sa.Column('ip_location', sa.String(length=100), nullable=True, comment='IP属地'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='用户代理字符串'),
    sa.Column('browser_type', sa.String(length=50), nullable=True, comment='浏览器类型'),
    sa.Column('os_type', sa.String(length=50), nullable=True, comment='操作系统类型'),
    sa.Column('device_type', sa.String(length=20), nullable=True, comment='设备类型'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='登录会话时长（秒）'),
    sa.Column('session_id', sa.String(length=128), nullable=True, comment='会话ID'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_core_login_log_is_deleted'), 'core_login_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_login_log_login_ip'), 'core_login_log', ['login_ip'], unique=False)
    op.create_index(op.f('ix_core_login_log_login_type'), 'core_login_log', ['login_type'], unique=False)
    op.create_index(op.f('ix_core_login_log_status'), 'core_login_log', ['status'], unique=False)
    op.create_index(op.f('ix_core_login_log_user_id'), 'core_login_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_core_login_log_username'), 'core_login_log', ['username'], unique=False)
    op.create_index('ix_login_log_ip_datetime', 'core_login_log', ['login_ip', 'sys_create_datetime'], unique=False)
    op.create_index('ix_login_log_status_datetime', 'core_login_log', ['status', 'sys_create_datetime'], unique=False)
    op.create_index('ix_login_log_type_datetime', 'core_login_log', ['login_type', 'sys_create_datetime'], unique=False)
    op.create_index('ix_login_log_user_datetime', 'core_login_log', ['user_id', 'sys_create_datetime'], unique=False)
    op.create_index('ix_login_log_user_type', 'core_login_log', ['user_id', 'login_type'], unique=False)
    op.create_index('ix_login_log_username_status', 'core_login_log', ['username', 'status'], unique=False)
    op.create_table('core_menu',
    sa.Column('parent_id', sa.String(length=21), nullable=True, comment='父菜单ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='菜单名称（路由名称）'),
    sa.Column('title', sa.String(length=100), nullable=True, comment='菜单标题（显示名称）'),
    sa.Column('authCode', sa.String(length=100), nullable=True, comment='后端权限标识'),
    sa.Column('path', sa.String(length=200), nullable=False, comment='路由路径'),
    sa.Column('type', sa.String(length=20), nullable=True, comment='菜单类型: catalog/menu/external/online_form/online_page'),
    sa.Column('component', sa.String(length=100), nullable=True, comment='组件路径'),
    sa.Column('redirect', sa.String(length=200), nullable=True, comment='重定向路径'),
    sa.Column('activePath', sa.String(length=200), nullable=True, comment='激活路径'),
    sa.Column('query', sa.JSON(), nullable=True, comment='额外路由参数'),
    sa.Column('noBasicLayout', sa.Boolean(), nullable=True, comment='无需基础布局'),
    sa.Column('icon', sa.String(length=100), nullable=True, comment='菜单图标'),
    sa.Column('activeIcon', sa.String(length=100), nullable=True, comment='激活图标'),
    sa.Column('order', sa.Integer(), nullable=True, comment='菜单排序'),
    sa.Column('hideInMenu', sa.Boolean(), nullable=True, comment='在菜单中隐藏'),
    sa.Column('hideChildrenInMenu', sa.Boolean(), nullable=True, comment='在菜单中隐藏下级'),
    sa.Column('hideInBreadcrumb', sa.Boolean(), nullable=True, comment='在面包屑中隐藏'),
    sa.Column('hideInTab', sa.Boolean(), nullable=True, comment='在标签栏中隐藏'),
    sa.Column('affixTab', sa.Boolean(), nullable=True, comment='固定在标签栏'),
    sa.Column('affixTabOrder', sa.Integer(), nullable=True, comment='标签栏固定顺序'),
    sa.Column('keepAlive', sa.Boolean(), nullable=True, comment='缓存页面'),
    sa.Column('maxNumOfOpenTab', sa.Integer(), nullable=True, comment='最大打开标签数'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='外链URL'),
    sa.Column('iframeSrc', sa.String(length=500), nullable=True, comment='内嵌iframe URL'),
    sa.Column('openInNewWindow', sa.Boolean(), nullable=True, comment='在新窗口打开'),
    sa.Column('badge', sa.String(length=20), nullable=True, comment='徽标内容'),
    sa.Column('badgeType', sa.String(length=20), nullable=True, comment='徽标类型: dot/normal'),
    sa.Column('badgeVariants', sa.String(length=20), nullable=True, comment='徽标颜色'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_menu_is_deleted'), 'core_menu', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_menu_parent_id'), 'core_menu', ['parent_id'], unique=False)
    op.create_table('core_message',
    sa.Column('recipient_id', sa.String(length=50), nullable=False, comment='接收人ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='消息标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('msg_type', sa.String(length=20), nullable=True, comment='消息类型: system/workflow/todo/announcement'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='消息状态: unread/read'),
    sa.Column('link_type', sa.String(length=50), nullable=True, comment='关联类型'),
    sa.Column('link_id', sa.String(length=50), nullable=True, comment='关联对象ID'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='阅读时间'),
    sa.Column('sender_id', sa.String(length=50), nullable=True, comment='发送人ID'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_message_is_deleted'), 'core_message', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_message_msg_type'), 'core_message', ['msg_type'], unique=False)
    op.create_index(op.f('ix_core_message_recipient_id'), 'core_message', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_core_message_status'), 'core_message', ['status'], unique=False)
    op.create_index('ix_message_recipient_status', 'core_message', ['recipient_id', 'status'], unique=False)
    op.create_index('ix_message_recipient_type', 'core_message', ['recipient_id', 'msg_type'], unique=False)
    op.create_table('core_permission',
    sa.Column('menu_id', sa.String(length=21), nullable=False, comment='关联菜单ID（逻辑外键关联core_menu）'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='权限名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='权限编码'),
    sa.Column('permission_type', sa.Integer(), nullable=True, comment='权限类型（0-按钮权限, 1-API权限, 2-数据权限, 3-其他权限）'),
    sa.Column('api_path', sa.String(length=200), nullable=True, comment='API路径'),
    sa.Column('http_method', sa.Integer(), nullable=True, comment='HTTP方法（0-GET, 1-POST, 2-PUT, 3-DELETE, 4-PATCH, 5-ALL）'),
    sa.Column('data_scope', sa.Integer(), nullable=True, comment='数据权限范围（0-全部, 1-仅本人, 2-本部门, 3-本部门及下级, 4-自定义）'),
    sa.Column('description', sa.Text(), nullable=True, comment='权限描述'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否启用'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_id', 'code', name='uq_permission_menu_code')
    )
    op.create_index(op.f('ix_core_permission_code'), 'core_permission', ['code'], unique=False)
    op.create_index(op.f('ix_core_permission_is_active'), 'core_permission', ['is_active'], unique=False)
    op.create_index(op.f('ix_core_permission_is_deleted'), 'core_permission', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_permission_menu_id'), 'core_permission', ['menu_id'], unique=False)
    op.create_index(op.f('ix_core_permission_name'), 'core_permission', ['name'], unique=False)
    op.create_index(op.f('ix_core_permission_permission_type'), 'core_permission', ['permission_type'], unique=False)
    op.create_table('core_post',
    sa.Column('name', sa.String(length=64), nullable=False, comment='岗位名称'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='岗位编码'),
    sa.Column('post_type', sa.Integer(), nullable=True, comment='岗位类型（0-管理岗, 1-技术岗, 2-业务岗, 3-职能岗, 4-其他）'),
    sa.Column('post_level', sa.Integer(), nullable=True, comment='岗位级别（0-高层, 1-中层, 2-基层, 3-一般员工）'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='岗位状态（启用/禁用）'),
    sa.Column('description', sa.Text(), nullable=True, comment='岗位描述/职责'),
    sa.Column('dept_id', sa.String(length=21), nullable=True, comment='所属部门ID（逻辑外键关联core_dept）'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_post_code'), 'core_post', ['code'], unique=True)
    op.create_index(op.f('ix_core_post_dept_id'), 'core_post', ['dept_id'], unique=False)
    op.create_index(op.f('ix_core_post_is_deleted'), 'core_post', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_post_name'), 'core_post', ['name'], unique=False)
    op.create_index(op.f('ix_core_post_post_level'), 'core_post', ['post_level'], unique=False)
    op.create_index(op.f('ix_core_post_post_type'), 'core_post', ['post_type'], unique=False)
    op.create_index(op.f('ix_core_post_status'), 'core_post', ['status'], unique=False)
    op.create_table('core_role',
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='角色编码'),
    sa.Column('role_type', sa.Integer(), nullable=True, comment='角色类型（0-系统角色, 1-自定义角色）'),
    sa.Column('status', sa.Boolean(), nullable=True, comment='角色状态（启用/禁用）'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='角色优先级（数字越大优先级越高）'),
    sa.Column('description', sa.Text(), nullable=True, comment='角色描述'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_role_code'), 'core_role', ['code'], unique=True)
    op.create_index(op.f('ix_core_role_is_deleted'), 'core_role', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_role_name'), 'core_role', ['name'], unique=False)
    op.create_index(op.f('ix_core_role_priority'), 'core_role', ['priority'], unique=False)
    op.create_index(op.f('ix_core_role_role_type'), 'core_role', ['role_type'], unique=False)
    op.create_index(op.f('ix_core_role_status'), 'core_role', ['status'], unique=False)
    op.create_table('core_scheduler_job',
    sa.Column('name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('code', sa.String(length=128), nullable=False, comment='任务编码'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('group', sa.String(length=64), nullable=True, comment='任务分组'),
    sa.Column('trigger_type', sa.String(length=20), nullable=True, comment='触发器类型'),
    sa.Column('cron_expression', sa.String(length=128), nullable=True, comment='Cron表达式'),
    sa.Column('interval_seconds', sa.Integer(), nullable=True, comment='间隔时间（秒）'),
    sa.Column('run_date', sa.DateTime(), nullable=True, comment='指定执行时间'),
    sa.Column('task_func', sa.String(length=256), nullable=False, comment='任务函数路径'),
    sa.Column('task_args', sa.Text(), nullable=True, comment='任务位置参数（JSON数组格式）'),
    sa.Column('task_kwargs', sa.Text(), nullable=True, comment='任务关键字参数（JSON对象格式）'),
    sa.Column('status', sa.Integer(), nullable=True, comment='任务状态（0-禁用，1-启用，2-暂停）'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='任务优先级'),
    sa.Column('max_instances', sa.Integer(), nullable=True, comment='最大实例数'),
    sa.Column('max_retries', sa.Integer(), nullable=True, comment='错误重试次数'),
    sa.Column('timeout', sa.Integer(), nullable=True, comment='超时时间（秒）'),
    sa.Column('coalesce', sa.Boolean(), nullable=True, comment='是否合并执行'),
    sa.Column('allow_concurrent', sa.Boolean(), nullable=True, comment='是否允许并发执行'),
    sa.Column('total_run_count', sa.Integer(), nullable=True, comment='总执行次数'),
    sa.Column('success_count', sa.Integer(), nullable=True, comment='成功次数'),
    sa.Column('failure_count', sa.Integer(), nullable=True, comment='失败次数'),
    sa.Column('last_run_time', sa.DateTime(), nullable=True, comment='最后执行时间'),
    sa.Column('next_run_time', sa.DateTime(), nullable=True, comment='下次执行时间'),
    sa.Column('last_run_status', sa.String(length=20), nullable=True, comment='最后执行状态'),
    sa.Column('last_run_result', sa.Text(), nullable=True, comment='最后执行结果'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_scheduler_job_code'), 'core_scheduler_job', ['code'], unique=True)
    op.create_index(op.f('ix_core_scheduler_job_group'), 'core_scheduler_job', ['group'], unique=False)
    op.create_index(op.f('ix_core_scheduler_job_is_deleted'), 'core_scheduler_job', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_scheduler_job_name'), 'core_scheduler_job', ['name'], unique=False)
    op.create_index(op.f('ix_core_scheduler_job_priority'), 'core_scheduler_job', ['priority'], unique=False)
    op.create_index(op.f('ix_core_scheduler_job_status'), 'core_scheduler_job', ['status'], unique=False)
    op.create_index(op.f('ix_core_scheduler_job_trigger_type'), 'core_scheduler_job', ['trigger_type'], unique=False)
    op.create_index('ix_scheduler_job_group_status', 'core_scheduler_job', ['group', 'status'], unique=False)
    op.create_index('ix_scheduler_job_next_run_status', 'core_scheduler_job', ['next_run_time', 'status'], unique=False)
    op.create_index('ix_scheduler_job_priority_status', 'core_scheduler_job', ['priority', 'status'], unique=False)
    op.create_index('ix_scheduler_job_status_trigger', 'core_scheduler_job', ['status', 'trigger_type'], unique=False)
    op.create_table('core_scheduler_log',
    sa.Column('job_id', sa.String(length=36), nullable=False, comment='任务ID'),
    sa.Column('job_name', sa.String(length=128), nullable=False, comment='任务名称'),
    sa.Column('job_code', sa.String(length=128), nullable=False, comment='任务编码'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='执行状态'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('duration', sa.Float(), nullable=True, comment='执行耗时（秒）'),
    sa.Column('result', sa.Text(), nullable=True, comment='执行结果'),
    sa.Column('exception', sa.Text(), nullable=True, comment='异常信息'),
    sa.Column('traceback', sa.Text(), nullable=True, comment='异常堆栈'),
    sa.Column('hostname', sa.String(length=128), nullable=True, comment='执行主机'),
    sa.Column('process_id', sa.Integer(), nullable=True, comment='进程ID'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='重试次数'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_scheduler_log_is_deleted'), 'core_scheduler_log', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_scheduler_log_job_code'), 'core_scheduler_log', ['job_code'], unique=False)
    op.create_index(op.f('ix_core_scheduler_log_job_id'), 'core_scheduler_log', ['job_id'], unique=False)
    op.create_index(op.f('ix_core_scheduler_log_job_name'), 'core_scheduler_log', ['job_name'], unique=False)
    op.create_index(op.f('ix_core_scheduler_log_start_time'), 'core_scheduler_log', ['start_time'], unique=False)
    op.create_index(op.f('ix_core_scheduler_log_status'), 'core_scheduler_log', ['status'], unique=False)
    op.create_index('ix_scheduler_log_code_start', 'core_scheduler_log', ['job_code', 'start_time'], unique=False)
    op.create_index('ix_scheduler_log_job_status', 'core_scheduler_log', ['job_id', 'status'], unique=False)
    op.create_index('ix_scheduler_log_status_start', 'core_scheduler_log', ['status', 'start_time'], unique=False)
    op.create_table('core_user',
    sa.Column('username', sa.String(length=150), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='是否超级管理员'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='邮箱'),
    sa.Column('mobile', sa.String(length=11), nullable=True, comment='手机号'),
    sa.Column('avatar', sa.String(length=36), nullable=True, comment='头像UUID'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='真实姓名'),
    sa.Column('gender', sa.Integer(), nullable=True, comment='性别'),
    sa.Column('user_type', sa.Integer(), nullable=True, comment='用户类型'),
    sa.Column('user_status', sa.Integer(), nullable=True, comment='用户状态'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='生日'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='所在城市'),
    sa.Column('address', sa.String(length=200), nullable=True, comment='详细地址'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='最后登录IP'),
    sa.Column('last_login_type', sa.String(length=20), nullable=True, comment='最后登录方式'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('dept_id', sa.String(length=21), nullable=True, comment='所属部门ID'),
    sa.Column('post_id', sa.String(length=21), nullable=True, comment='所属岗位ID'),
    sa.Column('role_id', sa.String(length=21), nullable=True, comment='所属角色ID'),
    sa.Column('manager_id', sa.String(length=21), nullable=True, comment='直属上级ID'),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True, comment='OAuth提供商'),
    sa.Column('gitee_id', sa.String(length=200), nullable=True, comment='Gitee用户ID'),
    sa.Column('github_id', sa.String(length=200), nullable=True, comment='GitHub用户ID'),
    sa.Column('qq_id', sa.String(length=200), nullable=True, comment='QQ用户openid'),
    sa.Column('google_id', sa.String(length=200), nullable=True, comment='Google用户ID'),
    sa.Column('wechat_unionid', sa.String(length=200), nullable=True, comment='微信UnionID'),
    sa.Column('wechat_openid', sa.String(length=200), nullable=True, comment='微信OpenID'),
    sa.Column('microsoft_id', sa.String(length=200), nullable=True, comment='Microsoft用户ID'),
    sa.Column('dingtalk_unionid', sa.String(length=200), nullable=True, comment='钉钉UnionID'),
    sa.Column('feishu_union_id', sa.String(length=200), nullable=True, comment='飞书UnionID'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_core_user_dept_id'), 'core_user', ['dept_id'], unique=False)
    op.create_index(op.f('ix_core_user_dingtalk_unionid'), 'core_user', ['dingtalk_unionid'], unique=True)
    op.create_index(op.f('ix_core_user_email'), 'core_user', ['email'], unique=False)
    op.create_index(op.f('ix_core_user_feishu_union_id'), 'core_user', ['feishu_union_id'], unique=True)
    op.create_index(op.f('ix_core_user_gitee_id'), 'core_user', ['gitee_id'], unique=True)
    op.create_index(op.f('ix_core_user_github_id'), 'core_user', ['github_id'], unique=True)
    op.create_index(op.f('ix_core_user_google_id'), 'core_user', ['google_id'], unique=True)
    op.create_index(op.f('ix_core_user_is_active'), 'core_user', ['is_active'], unique=False)
    op.create_index(op.f('ix_core_user_is_deleted'), 'core_user', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_core_user_is_superuser'), 'core_user', ['is_superuser'], unique=False)
    op.create_index(op.f('ix_core_user_last_login_type'), 'core_user', ['last_login_type'], unique=False)
    op.create_index(op.f('ix_core_user_microsoft_id'), 'core_user', ['microsoft_id'], unique=True)
    op.create_index(op.f('ix_core_user_mobile'), 'core_user', ['mobile'], unique=False)
    op.create_index(op.f('ix_core_user_name'), 'core_user', ['name'], unique=False)
    op.create_index(op.f('ix_core_user_oauth_provider'), 'core_user', ['oauth_provider'], unique=False)
    op.create_index(op.f('ix_core_user_post_id'), 'core_user', ['post_id'], unique=False)
    op.create_index(op.f('ix_core_user_qq_id'), 'core_user', ['qq_id'], unique=True)
    op.create_index(op.f('ix_core_user_role_id'), 'core_user', ['role_id'], unique=False)
    op.create_index(op.f('ix_core_user_user_status'), 'core_user', ['user_status'], unique=False)
    op.create_index(op.f('ix_core_user_user_type'), 'core_user', ['user_type'], unique=False)
    op.create_index(op.f('ix_core_user_username'), 'core_user', ['username'], unique=True)
    op.create_index(op.f('ix_core_user_wechat_openid'), 'core_user', ['wechat_openid'], unique=False)
    op.create_index(op.f('ix_core_user_wechat_unionid'), 'core_user', ['wechat_unionid'], unique=True)
    op.create_table('demo_cache',
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_cache_is_deleted'), 'demo_cache', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_demo_cache_title'), 'demo_cache', ['title'], unique=False)
    op.create_table('demos',
    sa.Column('title', sa.String(length=100), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='内容'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('id', sa.String(length=21), nullable=False, comment='主键ID(NanoId)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='是否删除'),
    sa.Column('sys_create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('sys_update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('sys_creator_id', sa.String(length=21), nullable=True, comment='创建人ID（逻辑外键关联core_user）'),
    sa.Column('sys_modifier_id', sa.String(length=21), nullable=True, comment='修改人ID（逻辑外键关联core_user）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demos_is_deleted'), 'demos', ['is_deleted'], unique=False)
    op.create_table('core_role_dept',
    sa.Column('role_id', sa.String(length=21), nullable=False),
    sa.Column('dept_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['core_dept.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'dept_id')
    )
    op.create_table('core_role_menu',
    sa.Column('role_id', sa.String(length=21), nullable=False),
    sa.Column('menu_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['core_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('core_role_permission',
    sa.Column('role_id', sa.String(length=21), nullable=False),
    sa.Column('permission_id', sa.String(length=21), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['core_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['core_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('core_role_permission')
    op.drop_table('core_role_menu')
    op.drop_table('core_role_dept')
    op.drop_index(op.f('ix_demos_is_deleted'), table_name='demos')
    op.drop_table('demos')
    op.drop_index(op.f('ix_demo_cache_title'), table_name='demo_cache')
    op.drop_index(op.f('ix_demo_cache_is_deleted'), table_name='demo_cache')
    op.drop_table('demo_cache')
    op.drop_index(op.f('ix_core_user_wechat_unionid'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_wechat_openid'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_username'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_user_type'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_user_status'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_role_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_qq_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_post_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_oauth_provider'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_name'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_mobile'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_microsoft_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_last_login_type'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_is_superuser'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_is_deleted'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_is_active'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_google_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_github_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_gitee_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_feishu_union_id'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_email'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_dingtalk_unionid'), table_name='core_user')
    op.drop_index(op.f('ix_core_user_dept_id'), table_name='core_user')
    op.drop_table('core_user')
    op.drop_index('ix_scheduler_log_status_start', table_name='core_scheduler_log')
    op.drop_index('ix_scheduler_log_job_status', table_name='core_scheduler_log')
    op.drop_index('ix_scheduler_log_code_start', table_name='core_scheduler_log')
    op.drop_index(op.f('ix_core_scheduler_log_status'), table_name='core_scheduler_log')
    op.drop_index(op.f('ix_core_scheduler_log_start_time'), table_name='core_scheduler_log')
    op.drop_index(op.f('ix_core_scheduler_log_job_name'), table_name='core_scheduler_log')
    op.drop_index(op.f('ix_core_scheduler_log_job_id'), table_name='core_scheduler_log')
    op.drop_index(op.f('ix_core_scheduler_log_job_code'), table_name='core_scheduler_log')
    op.drop_index(op.f('ix_core_scheduler_log_is_deleted'), table_name='core_scheduler_log')
    op.drop_table('core_scheduler_log')
    op.drop_index('ix_scheduler_job_status_trigger', table_name='core_scheduler_job')
    op.drop_index('ix_scheduler_job_priority_status', table_name='core_scheduler_job')
    op.drop_index('ix_scheduler_job_next_run_status', table_name='core_scheduler_job')
    op.drop_index('ix_scheduler_job_group_status', table_name='core_scheduler_job')
    op.drop_index(op.f('ix_core_scheduler_job_trigger_type'), table_name='core_scheduler_job')
    op.drop_index(op.f('ix_core_scheduler_job_status'), table_name='core_scheduler_job')
    op.drop_index(op.f('ix_core_scheduler_job_priority'), table_name='core_scheduler_job')
    op.drop_index(op.f('ix_core_scheduler_job_name'), table_name='core_scheduler_job')
    op.drop_index(op.f('ix_core_scheduler_job_is_deleted'), table_name='core_scheduler_job')
    op.drop_index(op.f('ix_core_scheduler_job_group'), table_name='core_scheduler_job')
    op.drop_index(op.f('ix_core_scheduler_job_code'), table_name='core_scheduler_job')
    op.drop_table('core_scheduler_job')
    op.drop_index(op.f('ix_core_role_status'), table_name='core_role')
    op.drop_index(op.f('ix_core_role_role_type'), table_name='core_role')
    op.drop_index(op.f('ix_core_role_priority'), table_name='core_role')
    op.drop_index(op.f('ix_core_role_name'), table_name='core_role')
    op.drop_index(op.f('ix_core_role_is_deleted'), table_name='core_role')
    op.drop_index(op.f('ix_core_role_code'), table_name='core_role')
    op.drop_table('core_role')
    op.drop_index(op.f('ix_core_post_status'), table_name='core_post')
    op.drop_index(op.f('ix_core_post_post_type'), table_name='core_post')
    op.drop_index(op.f('ix_core_post_post_level'), table_name='core_post')
    op.drop_index(op.f('ix_core_post_name'), table_name='core_post')
    op.drop_index(op.f('ix_core_post_is_deleted'), table_name='core_post')
    op.drop_index(op.f('ix_core_post_dept_id'), table_name='core_post')
    op.drop_index(op.f('ix_core_post_code'), table_name='core_post')
    op.drop_table('core_post')
    op.drop_index(op.f('ix_core_permission_permission_type'), table_name='core_permission')
    op.drop_index(op.f('ix_core_permission_name'), table_name='core_permission')
    op.drop_index(op.f('ix_core_permission_menu_id'), table_name='core_permission')
    op.drop_index(op.f('ix_core_permission_is_deleted'), table_name='core_permission')
    op.drop_index(op.f('ix_core_permission_is_active'), table_name='core_permission')
    op.drop_index(op.f('ix_core_permission_code'), table_name='core_permission')
    op.drop_table('core_permission')
    op.drop_index('ix_message_recipient_type', table_name='core_message')
    op.drop_index('ix_message_recipient_status', table_name='core_message')
    op.drop_index(op.f('ix_core_message_status'), table_name='core_message')
    op.drop_index(op.f('ix_core_message_recipient_id'), table_name='core_message')
    op.drop_index(op.f('ix_core_message_msg_type'), table_name='core_message')
    op.drop_index(op.f('ix_core_message_is_deleted'), table_name='core_message')
    op.drop_table('core_message')
    op.drop_index(op.f('ix_core_menu_parent_id'), table_name='core_menu')
    op.drop_index(op.f('ix_core_menu_is_deleted'), table_name='core_menu')
    op.drop_table('core_menu')
    op.drop_index('ix_login_log_username_status', table_name='core_login_log')
    op.drop_index('ix_login_log_user_type', table_name='core_login_log')
    op.drop_index('ix_login_log_user_datetime', table_name='core_login_log')
    op.drop_index('ix_login_log_type_datetime', table_name='core_login_log')
    op.drop_index('ix_login_log_status_datetime', table_name='core_login_log')
    op.drop_index('ix_login_log_ip_datetime', table_name='core_login_log')
    op.drop_index(op.f('ix_core_login_log_username'), table_name='core_login_log')
    op.drop_index(op.f('ix_core_login_log_user_id'), table_name='core_login_log')
    op.drop_index(op.f('ix_core_login_log_status'), table_name='core_login_log')
    op.drop_index(op.f('ix_core_login_log_login_type'), table_name='core_login_log')
    op.drop_index(op.f('ix_core_login_log_login_ip'), table_name='core_login_log')
    op.drop_index(op.f('ix_core_login_log_is_deleted'), table_name='core_login_log')
    op.drop_table('core_login_log')
    op.drop_index('ix_file_manager_storage_type', table_name='core_file_manager')
    op.drop_index('ix_file_manager_parent_type', table_name='core_file_manager')
    op.drop_index('ix_file_manager_md5', table_name='core_file_manager')
    op.drop_index(op.f('ix_core_file_manager_is_deleted'), table_name='core_file_manager')
    op.drop_table('core_file_manager')
    op.drop_index(op.f('ix_core_dict_item_value'), table_name='core_dict_item')
    op.drop_index(op.f('ix_core_dict_item_status'), table_name='core_dict_item')
    op.drop_index(op.f('ix_core_dict_item_label'), table_name='core_dict_item')
    op.drop_index(op.f('ix_core_dict_item_is_deleted'), table_name='core_dict_item')
    op.drop_index(op.f('ix_core_dict_item_dict_id'), table_name='core_dict_item')
    op.drop_table('core_dict_item')
    op.drop_index(op.f('ix_core_dict_status'), table_name='core_dict')
    op.drop_index(op.f('ix_core_dict_name'), table_name='core_dict')
    op.drop_index(op.f('ix_core_dict_is_deleted'), table_name='core_dict')
    op.drop_index(op.f('ix_core_dict_code'), table_name='core_dict')
    op.drop_table('core_dict')
    op.drop_index(op.f('ix_core_dept_status'), table_name='core_dept')
    op.drop_index(op.f('ix_core_dept_path'), table_name='core_dept')
    op.drop_index(op.f('ix_core_dept_parent_id'), table_name='core_dept')
    op.drop_index(op.f('ix_core_dept_name'), table_name='core_dept')
    op.drop_index(op.f('ix_core_dept_level'), table_name='core_dept')
    op.drop_index(op.f('ix_core_dept_is_deleted'), table_name='core_dept')
    op.drop_index(op.f('ix_core_dept_dept_type'), table_name='core_dept')
    op.drop_index(op.f('ix_core_dept_code'), table_name='core_dept')
    op.drop_table('core_dept')
    op.drop_index(op.f('ix_core_announcement_read_user_id'), table_name='core_announcement_read')
    op.drop_index(op.f('ix_core_announcement_read_is_deleted'), table_name='core_announcement_read')
    op.drop_index(op.f('ix_core_announcement_read_announcement_id'), table_name='core_announcement_read')
    op.drop_index('ix_announcement_read_unique', table_name='core_announcement_read')
    op.drop_table('core_announcement_read')
    op.drop_index(op.f('ix_core_announcement_status'), table_name='core_announcement')
    op.drop_index(op.f('ix_core_announcement_priority'), table_name='core_announcement')
    op.drop_index(op.f('ix_core_announcement_is_deleted'), table_name='core_announcement')
    op.drop_table('core_announcement')
    # ### end Alembic commands ###
